#!/bin/bash
set -ex

#use the Schaefer 400 variants that were warped to FSL MNI space using the CBIG_Projectfsaverage2MNI_Ants function
#Note that the CBIG_Projectfsaverage2MNI function is listed as obsolete when running CBIG code for Schaefer.
#Furthermore, visual inspection of the parcellation using the old and new projections reveals that the _Ants variants are
#beautifully coregistered, whereas the original variant (from the code on Github) is good but not perfect.
[ ! -d "high_res_originals" ] && mkdir "high_res_originals"
sz=2.3 #mm
Schaefer_srcdir=/gpfs/group/mnh5174/default/lab_resources/CBIG/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/MNI

cp ${Schaefer_srcdir}/Schaefer2018_400Parcels_7Networks_order_FSLMNI152_1mm_ants.nii.gz .

#NB. The Schaefer code produces the parcellation at different resolutions using FreeSurfer's mri_vol2vol. But using ResampleImageBySpacing (from ANTS)
#yields an identical file and can be used throughout this script with 1mm original inputs for consistency.
ResampleImageBySpacing 3 Schaefer2018_400Parcels_7Networks_order_FSLMNI152_1mm_ants.nii.gz Schaefer2018_400Parcels_7Networks_order_FSLMNI152_${sz}mm_ants.nii.gz ${sz} ${sz} ${sz} 0 1 1 #0 no smoothing, 1 for 1 voxel padding, 1 for nearest neighbor

immv Schaefer2018_400Parcels_7Networks_order_FSLMNI152_1mm_ants high_res_originals

#########
#CIT amygdala: 4 ROIs.
#ROI NUMBERING:
# 401 = l_bla
# 402 = r_bla
# 403 = l_cmn
# 404 = r_cmn

CIT_srcdir=/gpfs/group/mnh5174/default/lab_resources/parcellation/CIT168_Amygdala_v1.0.3/CIT168toMNI152_700um

cp ${CIT_srcdir}/CIT168_pAmyNuc_700um_MNI.nii.gz .

#create a BLA mask, which are the sub-briks 1 (BLN_La), 2 (BLN_BL), and 3 (BLN_BM)
fslroi CIT168_pAmyNuc_700um_MNI.nii.gz bln_la 0 1
#fslmaths bln_la -thr 0.4 -bin bln_la -odt char #threshold at 40% and binarize

fslroi CIT168_pAmyNuc_700um_MNI.nii.gz bln_bl 1 1
#fslmaths bln_bl -thr 0.4 -bin bln_bl -odt char #threshold at 40% and binarize

fslroi CIT168_pAmyNuc_700um_MNI.nii.gz bln_bm 2 1
#fslmaths bln_bm -thr 0.4 -bin bln_bm -odt char #threshold at 40% and binarize

#add individual masks and threshold if the voxel has at a summed 40% probability of being the basolateral nucleus
#use -fillh to remove any discontinuity in the mask (internal holes)
fslmaths bln_la -add bln_bl -add bln_bm -thr 0.4 -bin -fillh bla_combined -odt char

imrm bln_la bln_bl bln_bm #remove temporary images for each subnucleus

#separate left and right
3dcalc -overwrite -LPI -a bla_combined.nii.gz -expr 'a*isnegative(x)' -prefix l_bla.nii.gz
3dcalc -overwrite -LPI -a bla_combined.nii.gz -expr 'a*ispositive(x)' -prefix r_bla.nii.gz

#use cen + cmn for mask
fslroi CIT168_pAmyNuc_700um_MNI.nii.gz cen_prob 3 1
#fslmaths cen_prob -thr 0.4 -bin -fillh cen_mask -odt char

#separate left and right
#3dcalc -overwrite -LPI -a cen_mask.nii.gz -expr 'a*isnegative(x)' -prefix l_cen.nii.gz
#3dcalc -overwrite -LPI -a cen_mask.nii.gz -expr 'a*ispositive(x)' -prefix r_cen.nii.gz

#broader centromedial amygdala
fslroi CIT168_pAmyNuc_700um_MNI.nii.gz cmn_prob 4 1
#fslmaths bln_la -thr 0.4 -bin bln_la -odt char #threshold at 40% and binarize

#combine cen and cmn for mask
fslmaths cen_prob -add cmn_prob -thr 0.4 -bin -fillh cmn_combined -odt char

3dcalc -overwrite -LPI -a cmn_combined.nii.gz -expr 'a*isnegative(x)' -prefix l_cmn.nii.gz
3dcalc -overwrite -LPI -a cmn_combined.nii.gz -expr 'a*ispositive(x)' -prefix r_cmn.nii.gz

amy_inputs=(l_bla.nii.gz r_bla.nii.gz l_cmn.nii.gz r_cmn.nii.gz)
for a in "${amy_inputs[@]}"; do
    ResampleImageBySpacing 3 ${a} ${a/.nii.gz/}_${sz}mm.nii.gz ${sz} ${sz} ${sz} 0 1 1 #0 no smoothing, 1 for 1 voxel padding, 1 for nearest neighbor
    imrm "$a"
done

fslmaths l_bla_${sz}mm.nii.gz -add 400 -thr 401 l_bla_${sz}mm_401.nii.gz
fslmaths r_bla_${sz}mm.nii.gz -add 401 -thr 402 r_bla_${sz}mm_402.nii.gz
fslmaths l_cmn_${sz}mm.nii.gz -add 402 -thr 403 l_cmn_${sz}mm_403.nii.gz
fslmaths r_cmn_${sz}mm.nii.gz -add 403 -thr 404 r_cmn_${sz}mm_404.nii.gz

imrm l_bla_${sz}mm r_bla_${sz}mm l_cmn_${sz}mm r_cmn_${sz}mm bla_combined cmn_combined cen_prob cmn_prob
immv CIT168_pAmyNuc_700um_MNI high_res_originals

######
#thalamus
## ROIs are 405-408 for L; 409-412 for R
Thalamus_srcdir=$FSLDIR/data/atlases/Thalamus
cp ${Thalamus_srcdir}/Thalamus-maxprob-thr50-1mm.nii.gz .

ResampleImageBySpacing 3 Thalamus-maxprob-thr50-1mm.nii.gz Thalamus-maxprob-thr50-${sz}mm.nii.gz ${sz} ${sz} ${sz} 0 1 1 #0 no smoothing, 1 for 1 voxel padding, 1 for nearest neighbor

#ROIs 1, 2, 3 are tiny and should be dropped
fslmaths Thalamus-maxprob-thr50-${sz}mm -thr 3.5 -sub 3 -thr 0 Thalamus-maxprob-thr50-${sz}mm_rm123 #second -thr 0 gets rid of the -3 generated by the -sub command

3dcalc -overwrite -LPI -a Thalamus-maxprob-thr50-${sz}mm_rm123.nii.gz -expr 'a*isnegative(x)' -prefix l_thal_${sz}mm.nii.gz
3dcalc -overwrite -LPI -a Thalamus-maxprob-thr50-${sz}mm_rm123.nii.gz -expr 'a*ispositive(x)' -prefix r_thal_${sz}mm.nii.gz

fslmaths l_thal_${sz}mm -add 404 -thr 405 l_thal_${sz}_renumber
fslmaths r_thal_${sz}mm -add 408 -thr 409 r_thal_${sz}_renumber

#cleanup
imrm l_thal_${sz}mm r_thal_${sz}mm Thalamus-maxprob-thr50-${sz}mm_rm123 Thalamus-maxprob-thr50-${sz}mm
immv Thalamus-maxprob-thr50-1mm high_res_originals

#########
#Choi 2012 striatum (per Nate: use tight mask)

#this command from freesurfer will transform the Freesurfer-space 256^3 RSP Choi original to the standard FSL MNI space without interpolation
#the --regheader tells the command to apply an identity transformation such that only the grid extents and orientation are modified to match the --targ (template)
mri_vol2vol --targ $FSLDIR/data/standard/MNI152lin_T1_1mm_brain.nii.gz --regheader \
	    --mov /gpfs/group/mnh5174/default/lab_resources/parcellation/Choi_JNeurophysiol12_MNI152/Choi2012_7Networks_MNI152_FreeSurferConformed1mm_TightMask.nii.gz \
	    --o Choi2012_7Networks_MNI152_1mm_TightMask.nii.gz

ResampleImageBySpacing 3 Choi2012_7Networks_MNI152_1mm_TightMask.nii.gz Choi2012_7Networks_MNI152_${sz}mm_TightMask.nii.gz ${sz} ${sz} ${sz} 0 1 1 #0 no smoothing, 1 for 1 voxel padding, 1 for nearest neighbor

3dcalc -overwrite -LPI -a Choi2012_7Networks_MNI152_${sz}mm_TightMask.nii.gz -expr 'a*isnegative(x)' -prefix l_striatum_tight_7Networks_${sz}mm.nii.gz
3dcalc -overwrite -LPI -a Choi2012_7Networks_MNI152_${sz}mm_TightMask.nii.gz -expr 'a*ispositive(x)' -prefix r_striatum_tight_7Networks_${sz}mm.nii.gz

#note that ROIs 1 and 3 in the original 1mm space are tiny and largely disappear when resampling to 2.3mm. Thus, drop these explicitly.
# > library(oro.nifti)
# oro.nifti 0.9.1
# > x <- readNIfTI("l_striatum_tight_7Networks_2.3mm.nii.gz")
# > table(x)
# x
# 0           2      4      5      6      7
# 585784    114    164     86    241    265

# > x <- readNIfTI("r_striatum_tight_7Networks_2.3mm.nii.gz")
# > table(x)
# x
# 0           2      3      4      5      6      7
# 585834     97      9    189     80    306    139

#this is accomplished using this little fixer script
R CMD BATCH --no-save --no-restore fix_striatum_rois.R

fslmaths l_striatum_tight_7Networks_${sz}mm -add 412 -thr 413 l_striatum_tight_7Networks_${sz}mm_renumber
fslmaths r_striatum_tight_7Networks_${sz}mm -add 417 -thr 418 r_striatum_tight_7Networks_${sz}mm_renumber

#result: l striatum ROIs are 413-417; 4 striatum ROIs are 418-422

imrm l_striatum_tight_7Networks_${sz}mm r_striatum_tight_7Networks_${sz}mm
immv Choi2012_7Networks_MNI152_1mm_TightMask.nii.gz high_res_originals

#verified that inputs match template for ALL final files. Example.
#3dinfo -header_line -same_all_grid Schaefer2018_400Parcels_7Networks_order_FSLMNI152_2.3mm_ants.nii.gz /gpfs/group/mnh5174/default/lab_resources/standard/fsl_mni152/MNI152_T1_2.3mm.nii

fslmaths Schaefer2018_400Parcels_7Networks_order_FSLMNI152_2.3mm_ants -add l_bla_${sz}mm_401 -add r_bla_${sz}mm_402 -add l_cmn_${sz}mm_403 -add r_cmn_${sz}mm_404 \
	 -add l_thal_${sz}_renumber -add r_thal_${sz}_renumber -add l_striatum_tight_7Networks_${sz}mm_renumber -add r_striatum_tight_7Networks_${sz}mm_renumber \
	 Schaefer_422_final_jul2018

#sanity check on final file
#library(oro.nifti)
#x <- readNIfTI("Schaefer_422_final_jul2018.nii.gz", reorient=F)
#sort(unique(as.vector(x)))
#all.equal(sort(unique(as.vector(x))), 0:422)
#TRUE

#Thus, no overlaps leading to ROIs outside the 1-422 range
#CHECK ME IN DETAIL:
#fsleyes $FSLDIR/data/standard/MNI152_T1_1mm.nii.gz $MRI_STDDIR/fsl_mni152/MNI152_T1_2.3mm.nii Schaefer_422_final_jul2018.nii.gz high_res_originals/*
